name: publish module keycloak
on:
  create:
    tags:
      - keycloak-v*
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install and Build
        run: sh build.sh
      - name: Move to Keycloak Folder
        run: cd packages/keycloak
      - name: Publish Keycloak
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}