name: publish docs
on:
  push:
    tags:
      - docs-v*
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Publish
        env:
          GIT_USER: sergiofilhowz
          CURRENT_BRANCH: master
          USE_SSH: true
        run: |
          mkdir ~/.ssh
          sudo chmod 700 ~/.ssh
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          sudo chmod 700 ~/.ssh/id_rsa
          cd ./site/website
          yarn
          yarn run publish-gh-pages