name: test-integration
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Permissions
        run: chmod -R 666 ./
      - name: Permissions
        run: chown -R node ./
      - name: Test
        run: docker-compose up --exit-code-from web